# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anii.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 536)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/source/1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setMinimumSize(QtCore.QSize(240, 155))
        self.label_1.setMaximumSize(QtCore.QSize(240, 155))
        self.label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_1.setText("")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(240, 155))
        self.label_2.setMaximumSize(QtCore.QSize(240, 155))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(240, 240))
        self.label_3.setMaximumSize(QtCore.QSize(240, 240))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMaximumSize(QtCore.QSize(100, 20))
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(239)
        self.spinBox.setProperty("value", 120)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setMaximumSize(QtCore.QSize(100, 20))
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setMaximum(239)
        self.spinBox_2.setProperty("value", 120)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout.addWidget(self.spinBox_2)
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setMaximumSize(QtCore.QSize(100, 20))
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setMaximum(154)
        self.spinBox_3.setProperty("value", 78)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout.addWidget(self.spinBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/source/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen.setIcon(icon1)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionnext = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/source/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionnext.setIcon(icon2)
        self.actionnext.setObjectName("actionnext")
        self.actionback = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/source/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionback.setIcon(icon3)
        self.actionback.setObjectName("actionback")
        self.actionsaveas = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/source/6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsaveas.setIcon(icon4)
        self.actionsaveas.setObjectName("actionsaveas")
        self.actiondel = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/source/13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiondel.setIcon(icon5)
        self.actiondel.setObjectName("actiondel")
        self.actionfusion = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/source/14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionfusion.setIcon(icon6)
        self.actionfusion.setObjectName("actionfusion")
        self.actionet2tc = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/source/et.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionet2tc.setIcon(icon7)
        self.actionet2tc.setObjectName("actionet2tc")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionnormalize = QtWidgets.QAction(MainWindow)
        self.actionnormalize.setObjectName("actionnormalize")
        self.actionlines = QtWidgets.QAction(MainWindow)
        self.actionlines.setObjectName("actionlines")
        self.actionnewwindow = QtWidgets.QAction(MainWindow)
        self.actionnewwindow.setObjectName("actionnewwindow")
        self.actionwt2tc = QtWidgets.QAction(MainWindow)
        self.actionwt2tc.setObjectName("actionwt2tc")
        self.actiontc2wt = QtWidgets.QAction(MainWindow)
        self.actiontc2wt.setObjectName("actiontc2wt")
        self.actiondirectory = QtWidgets.QAction(MainWindow)
        self.actiondirectory.setObjectName("actiondirectory")
        self.actionopeninnew = QtWidgets.QAction(MainWindow)
        self.actionopeninnew.setObjectName("actionopeninnew")
        self.actionsaveslinum = QtWidgets.QAction(MainWindow)
        self.actionsaveslinum.setObjectName("actionsaveslinum")
        self.actionrestoreslinum = QtWidgets.QAction(MainWindow)
        self.actionrestoreslinum.setObjectName("actionrestoreslinum")
        self.actionrmregion = QtWidgets.QAction(MainWindow)
        self.actionrmregion.setObjectName("actionrmregion")
        self.actionrmlabel = QtWidgets.QAction(MainWindow)
        self.actionrmlabel.setObjectName("actionrmlabel")
        self.actionrmfocus = QtWidgets.QAction(MainWindow)
        self.actionrmfocus.setObjectName("actionrmfocus")
        self.actionnextsp = QtWidgets.QAction(MainWindow)
        self.actionnextsp.setObjectName("actionnextsp")
        self.actionlastsp = QtWidgets.QAction(MainWindow)
        self.actionlastsp.setObjectName("actionlastsp")
        self.actionsamesp = QtWidgets.QAction(MainWindow)
        self.actionsamesp.setObjectName("actionsamesp")
        self.actionslicesave = QtWidgets.QAction(MainWindow)
        self.actionslicesave.setObjectName("actionslicesave")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionsaveas)
        self.menu.addAction(self.actionslicesave)
        self.menu.addAction(self.actiondirectory)
        self.menu.addAction(self.actiondel)
        self.menu.addAction(self.actionexit)
        self.menu_2.addAction(self.actionnormalize)
        self.menu_2.addAction(self.actionlines)
        self.menu_2.addAction(self.actionnewwindow)
        self.menu_2.addAction(self.actionopeninnew)
        self.menu_2.addAction(self.actionsaveslinum)
        self.menu_2.addAction(self.actionrestoreslinum)
        self.menu_2.addAction(self.actionsamesp)
        self.menu_2.addAction(self.actionnextsp)
        self.menu_2.addAction(self.actionlastsp)
        self.menu_3.addAction(self.actionet2tc)
        self.menu_3.addAction(self.actionwt2tc)
        self.menu_3.addAction(self.actiontc2wt)
        self.menu_3.addAction(self.actionfusion)
        self.menu_3.addAction(self.actionrmfocus)
        self.menu_3.addAction(self.actionrmregion)
        self.menu_3.addAction(self.actionrmlabel)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addAction(self.actionsaveas)
        self.toolBar.addAction(self.actiondel)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionback)
        self.toolBar.addAction(self.actionnext)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionfusion)
        self.toolBar.addAction(self.actionet2tc)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsaveslinum)
        self.toolBar.addAction(self.actionrestoreslinum)

        self.retranslateUi(MainWindow)
        self.actionopen.triggered.connect(MainWindow.file_open)
        self.actionback.triggered.connect(MainWindow.back)
        self.actionnext.triggered.connect(MainWindow.next)
        self.actionexit.triggered.connect(MainWindow.close)
        self.spinBox.valueChanged['int'].connect(MainWindow.nii_show)
        self.spinBox_2.valueChanged['int'].connect(MainWindow.nii_show)
        self.spinBox_3.valueChanged['int'].connect(MainWindow.nii_show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HAI-图像"))
        self.label_4.setText(_translate("MainWindow", "sagittal"))
        self.label_5.setText(_translate("MainWindow", "coronal"))
        self.label_6.setText(_translate("MainWindow", "axial"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "视图"))
        self.menu_3.setTitle(_translate("MainWindow", "处理"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionopen.setToolTip(_translate("MainWindow", "打开"))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionexit.setText(_translate("MainWindow", "退出"))
        self.actionexit.setShortcut(_translate("MainWindow", "F4"))
        self.actionnext.setText(_translate("MainWindow", "下一张"))
        self.actionnext.setShortcut(_translate("MainWindow", "Right"))
        self.actionback.setText(_translate("MainWindow", "上一张"))
        self.actionback.setShortcut(_translate("MainWindow", "Left"))
        self.actionsaveas.setText(_translate("MainWindow", "另存为"))
        self.actionsaveas.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actiondel.setText(_translate("MainWindow", "删除"))
        self.actiondel.setShortcut(_translate("MainWindow", "Del"))
        self.actionfusion.setText(_translate("MainWindow", "融合"))
        self.actionet2tc.setText(_translate("MainWindow", "et2tc"))
        self.actionsave.setText(_translate("MainWindow", "保存"))
        self.actionnormalize.setText(_translate("MainWindow", "标准化"))
        self.actionlines.setText(_translate("MainWindow", "指示线"))
        self.actionnewwindow.setText(_translate("MainWindow", "新窗口"))
        self.actionwt2tc.setText(_translate("MainWindow", "wt2tc"))
        self.actiontc2wt.setText(_translate("MainWindow", "tc2wt"))
        self.actiondirectory.setText(_translate("MainWindow", "所在文件夹"))
        self.actionopeninnew.setText(_translate("MainWindow", "新窗口打开"))
        self.actionsaveslinum.setText(_translate("MainWindow", "保存视图"))
        self.actionrestoreslinum.setText(_translate("MainWindow", "还原idx"))
        self.actionrmregion.setText(_translate("MainWindow", "清除区域（选）"))
        self.actionrmlabel.setText(_translate("MainWindow", "清除标签"))
        self.actionrmfocus.setText(_translate("MainWindow", "清除区域（线）"))
        self.actionnextsp.setText(_translate("MainWindow", "下一样本"))
        self.actionlastsp.setText(_translate("MainWindow", "上一样本"))
        self.actionsamesp.setText(_translate("MainWindow", "同样本"))
        self.actionslicesave.setText(_translate("MainWindow", "保存切片"))

import anii_rc
